### ISSUE TITLE
DECOMPILE_DLG_TO_D issue in WeiDU v241

### ISSUE THREAD

**Issue by badungu** [WeiDUorg/weidu#100]
Hello again,

tried to install EET today with WeiDU and the installation fails during compiling the extracted dialogues from BG1EE. I investigated the problem and EET is using DECOMPILE_DLG_TO_D before compiling it again, so I tried to reproduce it like this:

```
COPY_EXISTING ~BDGARRIC.DLG~ ~override~
DECOMPILE_DLG_TO_D
COMPILE_D_TO_DLG
```

The installation fails with the following error:

```
[BDGARRIC.DLG] PARSE ERROR at line 12 column 1-11
Near Text: Garrick
        syntax error

[BDGARRIC.DLG]  ERROR at line 12 column 1-11
Near Text: Garrick
        Parsing.Parse_error
ERROR: parsing [BDGARRIC.DLG]: Parsing.Parse_error
ERROR: [BDGARRIC.DLG] -> [BDGARRIC.D] Patching Failed (COPY) (Parsing.Parse_erro
r)
Stopping installation because of error.
```

If I only use DECOMPILE_DLG_TO_D without compiling it again, the failing block looks like this:
```
IF ~  OR(2)
AreaCheck("BD0120")
AreaCheck("BD0130")
GlobalGT("bd_joined","locals",0)
~ THEN BEGIN 0
  SAY #66441
  IF ~  OR(2)
!Range("ff_camp",999)
!TriggerOverride("ff_camp",IsOverMe("garrick"))
// ~Garrick~
~ THEN REPLY #66442 DO ~SetGlobal("bd_npc_camp","locals",1)
~ GOTO 1
  IF ~~ THEN REPLY #66443 GOTO 2
  IF ~~ THEN REPLY #66444 GOTO 1
END
```

Line 12 in this case is `// ~Garrick~`...

Thanks for looking into this. :)

Edit: Tried DECOMPILE_AND_PATCH and also got the same error. 

Greetings
badungu

**Comment by FredrikLindgren** [comment]
Fixed. Regression introduced in 43095451a209dd9efaf932482721434faec0c630.
