### ISSUE TITLE
AT_NOW ignores exit status

### ISSUE THREAD

**Issue by lynxlynxlynx** [WeiDUorg/weidu#105]
Eg., sticking `AT_NOW ~exit 11~` in a tp2 won't make it fail.

Is this intentional?

Background: I'm trying to fix 10pp to work with wonky parent dirs and it offloads most of the work to perl via AT_NOW. So if something goes wrong there, weidu doesn't register it and happily finishes installing a broken mod.

**Comment by FredrikLindgren** [comment]
Yes, WeiDU explicitly ignores the return value of the inferior process.

I'm not sure I can start making it fail on this without causing problems in the wild. It probably goes without saying that something like perl programs are likely outside the scope of AT_*.

**Comment by lynxlynxlynx** [comment]
Sure, perl is just my use case (and maybe SSL using mods). Anything you run, you can't detect failures in.

Maybe an extra optional parameter, so there's backward compatibility?

**Comment by FredrikLindgren** [comment]
Implemented. Sorry about the delay.
`AT_NOW foo ~exit 11~` will result in the variable `%foo%` evaluating to 11.
