### ISSUE TITLE
fj_are_struct corrupts ARE resources in PST

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#109]
The `projectile` offset definition overlaps with the `note` count definition for PST ([code](https://github.com/WeiDUorg/weidu/blob/devel/src/tph/include/fj_are_struct.tpa#L277)):
```
PATCH_IF is_pst BEGIN
  TEXT_SPRINT $struct(0xc8 0xcc 0x04 0x214) note
END ELSE BEGIN
  TEXT_SPRINT $struct(0xc4 0xc8 0x04 0x034) note
END
TEXT_SPRINT $struct(0xcc 0xd0 0x04 0x01c) projectile
```

Projectile structures are not available in the ARE V1.0 variant for PST.

**Comment by FredrikLindgren** [comment]
Fixed. The function will only sprint projectiles in the ELSE branch.
