### ISSUE TITLE
fj_are_structure should be able to set dialog resrefs to region structures in PSTEE

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#111]
The region parameter `fj_dialog` is currently only available for [classic PST](https://github.com/WeiDUorg/weidu/blob/master/src/tph/include/fj_are_struct.tpa#L628). The PSTEE engine supports this field as well.

**Comment by FredrikLindgren** [comment]
I'll just remove the conditional.

**Comment by FredrikLindgren** [comment]
Done.
