### ISSUE TITLE
Request: Allow fj_are_structure regions to define all available PST(EE)-specific fields

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#112]
In addition to dialog resrefs PST and PSTEE allow [several more fields](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Info) to be defined, but are not yet supported by `fj_are_structure`:
- Sound (resref) at offset 0xac
- Talk location point X coordinate (short) at offset 0xb4
- Talk location point Y coordinate (short) at offset 0xb6
- Speaker name (strref) at offset 0xb8

**Comment by FredrikLindgren** [comment]
Done.
