### ISSUE TITLE
Controlled termination of the installation process

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#118]
There is currently no way (I know of) to cancel the install process once a component has been selected for installation, except by using `FAIL` which triggers the full procedure of showing the error stack and marking the component as "failed".

Would it be feasible to add an option for a controlled termination of an ongoing installation, which rolls back the current progress and shows a user-defined message, but doesn't show error stack or mark component as failed? Maybe via an optional parameter to `FAIL`?

**Comment by FredrikLindgren** [comment]
Conceptually it is not very problematic. Implementation remains to be seen. What would you want to call this thing? It won't be an option to FAIL.

**Comment by Argent77** [comment]
`ABORT`, `CANCEL` or `EXIT` would be suitable names. My favorite is `ABORT`.

**Comment by FredrikLindgren** [comment]
Tentatively implemented in 2379bafa63318d8ebfb51b446567d9f9808a628b.

Like FAIL and WARN, ABORT will prompt the user to press a key before the process exits and like FAIL, when components are installed interactively, an aborted component will be re-prompted until the user selects [N]ot Install or [Q]uit.

**Comment by Argent77** [comment]
I agree with that. A controlled `ABORT` should not count as failed, as there can be all kinds of (valid) reasons for it. There is always `FAIL` for cases where the mod has to communicate a more serious issue.

**Comment by FredrikLindgren** [comment]
As of latest commit, ABORT does none of those things, and more!

**Comment by FredrikLindgren** [comment]
Feel free to reopen if it needs more work.
