### ISSUE TITLE
[LINUX] File operations do not work with absolute file paths

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#124]
Using absolute file paths in file operations doesn't work on Linux. I've tested it on a case-insensitive filesystem (JFS with OS/2 compatibility). Windows and macOS don't seem to be affected by this issue.

Test script:
```
ACTION_IF (FILE_EXISTS ~chitin.key~) BEGIN
  PRINT ~Found relative file.~
END ELSE BEGIN
  PRINT ~NOT found relative file.~
END

ACTION_IF (~%WEIDU_OS%~ STR_EQ ~win32~) BEGIN
  AT_NOW ~echo %cd% >a7test.txt~
END ELSE BEGIN
  AT_NOW ~pwd >a7test.txt~
END
COPY - ~a7test.txt~ ~a7test.txt~
  SET pos = INDEX_BUFFER(~ *[%WNL%]~)
  PATCH_IF (pos >= 0) BEGIN
    READ_ASCII 0 path (pos) NULL
  END ELSE BEGIN
    TEXT_SPRINT path ~.~
  END
DELETE + ~a7test.txt~
PRINT ~Absolute path = "%path%"~

ACTION_IF (FILE_EXISTS ~%path%/chitin.key~) BEGIN
  PRINT ~Found absolute file.~
END ELSE BEGIN
  PRINT ~NOT found absolute file.~
END
```

Both FILE_EXISTS and COPY have been confirmed not working. It's likely that other file operations don't work either.

**Comment by Argent77** [comment]
**Update:**
It's apparently caused by the combination of auto-tolower enforced by the WeiDU binary in combination with the case-insensitive partition mounted in a folder of a case-sensitive filesystem. I was able to provoke the same issue by extending the relative path to the case-sensitive parent filesystem.

Is there a way to turn off the tolower functionality by command line option?

**Comment by FredrikLindgren** [comment]
There presently is no way of turning off the lowercasing employed by the Linux binary. Would the ability to turn it off be useful? Seems to me like you'd effectively lose the ability to install mods, unless the mod was bespoke for whatever game and mod-stack you would be installing it on, since it would have to be case-exact at the time of installation.

**Comment by Argent77** [comment]
I stumbled over this particular side effect when I tried to install EET, which requires the full path to the BGEE installation.

Disabling lowercasing will be useful for games that are installed on a case-insensitive partition. From what I've seen lowercasing seems to be exclusively handled by the `case_ins_xxx.ml` files. Adding a way to turn it off on demand (e.g. via cmdline option or environment variable) should not be impossible to implement.

**Comment by FredrikLindgren** [comment]
Done in 1bdf5bc677d83d178ec195af9d98c5b3eb96f250.

**Comment by Argent77** [comment]
Thank you. It seems to work fine with all the regular WeiDU commands.

However, I found one issue that may cause trouble indirectly. The command `(ACTION|PATCH)_BASH_FOR` stores matching paths into BASH_FOR_* variables in all uppercase. Subsequent commands that make use of them may fail to function because of this.
