### ISSUE TITLE
Allow use of variables in FLAGS parameter for dialog transitions

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#125]
EE games provide additional flags that can be used in dialog transitions. WeiDU allows you to set these flags by the `FLAGS` feature. But currently it is only possible to specify a single literal number as argument.

Since these flags correspond to individual bits, it would be helpful to use one or more of the predefined BITx constants (or maybe a mix of numbers and variables), as outlined in the example below.

Example:
```
IF ~~ Test
  SAY ~Statement...~
  ++ ~Reply 1~ DO ~SetGlobal("x","GLOBAL",1)~ FLAGS 512 + Test1           // Allowed
  ++ ~Reply 2~ DO ~SetGlobal("x","GLOBAL",1)~ FLAGS BIT9 + Test2          // NOT allowed
  ++ ~Reply 3~ DO ~SetGlobal("x","GLOBAL",1)~ FLAGS (BIT9+BIT10) + Test3  // Also NOT allowed
END
```

Alternatively, adding new keywords for the [flags](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/dlg_v1.htm#formDLGV1_Transition) "Execute immediate" (bit9) and "Clear actions" (bit 10) might be a solution.

**Comment by FredrikLindgren** [comment]
I'm going to have to refer you to using TP2 variables in the D and compiling with EVAL. D has no concept of variables, to say nothing of arithmetic.
