### ISSUE TITLE
[WeiDU v246] REPLACE_BCS_BLOCK needs a better documentation or a clear tutorial

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#128]
Pretty much what the title says. In particular, the following information is missing:
it (the patch) can replace multiple blocks only if they're **consecutive**. For example, if oldFile contains the first block and the last block of a certain _.bcs_ file, the patch won't get executed.....

**Comment by FredrikLindgren** [comment]
The [documentation](http://weidu.org/~thebigg/README-WeiDU.html#REPLACE_BCS_BLOCK) states that oldFile is matched as a segment, which implies that disjoint parts cannot be matched. I can add this sentence if you like:

> Multiple blocks can be replaced if they are contiguous and in order.

**Comment by 4Luke4** [comment]
> I can add this sentence if you like:
> 
> > Multiple blocks can be replaced if they are contiguous and in order.

Yeah, it's probably clearer.....
