### ISSUE TITLE
APPLY_BCS_PATCH needs a proper documentation/tutorial

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#129]
There is no documentation about this instruction. How am I supposed to use it?

**Comment by FredrikLindgren** [comment]
Can you be more specific?
[APPLY_BCS_PATCH](http://weidu.org/~thebigg/README-WeiDU.html#APPLY_BCS_PATCH) explains what it does, albeit a bit tersely, and links to [--bcmp-from](http://weidu.org/~thebigg/README-WeiDU.html#--bcmp-from) et al. for further info on how to obtain a patch file. Where do you feel the documentation is lacking?

**Comment by 4Luke4** [comment]
> Where do you feel the documentation is lacking?

Maybe here?
_Applies patchFile to the current file. See --bcmp-from and similar command-line arguments for constructing these patches._

**Comment by 4Luke4** [comment]
To tell the truth, I'm not sure APPLY_BCS_PATCH is what I need...... I'm looking for the most effective way of patching BCS scripts: in particular, I need to add a trigger every time the AI casts certain spells..... I know I can do this with REPLACE_BCS_BLOCK but I think it's too much time consuming, so I was wondering if APPLY_BCS_PATCH is better in this case......

**Comment by FredrikLindgren** [comment]
It's not.
Your best bet is probably `COPY_EXISTING_REGEXP` and `REPLACE_TEXTUALLY`.

If we are done here I'll close this issue.

**Comment by 4Luke4** [comment]
> It's not.
> Your best bet is probably `COPY_EXISTING_REGEXP` and `REPLACE_TEXTUALLY`.
> 
> If we are done here I'll close this issue.

True, but I'm limited to match a single trigger..... In order to be safe, I'd like to do something like this:
```
COPY_EXISTING_REGEXP ~.*\.bcs~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY
	 ~General(LastSeenBy,HUMANOID)
	!StateCheck(LastSeenBy,STATE_DISABLED)~
	 ~General(LastSeenBy,HUMANOID)
	!CheckSpellState(LastSeenBy,UNDISPELLABLE)
	!StateCheck(LastSeenBy,STATE_DISABLED)~
  END
BUT_ONLY
```
Unfortunately, this doesn't work..........

**Comment by FredrikLindgren** [comment]
Your regexp does not match the contents of the buffer. You assume tab indentation and whatever newline format you use for your TP2. WeiDU decompiles with LNL (\n) and 2 spaces of indentation.

There are additional issues that could cause issues on vanilla and/or non-EE games, but I assume you've got that covered.

**Comment by 4Luke4** [comment]
> Your regexp does not match the contents of the buffer. You assume tab indentation and whatever newline format you use for your TP2. WeiDU decompiles with LNL (\n) and 2 spaces of indentation.

What do you mean exactly? I didn't managed to fix the issue via removing tab indentation.....

**Comment by FredrikLindgren** [comment]
A dummy script decompiles into the following BAF:
```
IF
  General(LastSeenBy,HUMANOID)
  !StateCheck(LastSeenBy,STATE_DISABLED)
THEN
  RESPONSE #100
    Continue()
END
```
When you want to match several lines, you need to account for the kind of newlines used. To be on the safe side, that means accounting for all kinds. Additionally, it's a good idea to account for both tabs and spaces and not make any assumptions about the number of any of these things. Although WeiDU is predictable in what it uses, regexps errors are annoying and playing it safe tends to reduce the number of those.
```
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY
      ~General(LastSeenBy,HUMANOID)[%WNL%%TAB% ]*!StateCheck(LastSeenBy,STATE_DISABLED)~
      ~General(LastSeenBy,HUMANOID)
      !StateCheck(LastSeenBy,UNDISPELLABLE)
      !StateCheck(LastSeenBy,STATE_DISABLED)~
  END
```
Note that WNL is a composite of \r and \n and thus matches both characters as well as any sequence of them, when used inside a character set like this.
