### ISSUE TITLE
ADD_MEMORIZED_SPELL should work correctly with innate SPLs

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#130]
`ADD_MEMORIZED_SPELL ~spcl321~ #0 ~INNATE~ (2)`

The previous instruction does nothing (if you check the CRE with NearInfinity, you'll notice that BERSERKER_RAGE is not listed under the _Memorized spells_ section.......

I know you can achieve the same goal with ADD_CRE_EFFECT (opcode = 171), but I'd like to report this issue in any case (since the ReadMe states that ADD_MEMORIZED_SPELL works for innate SPLs.....)

EDIT: OK, sorry, it seems to work fine now, maybe I was writing `#2` instead of `(2)` (I'm referring to `[(value)]`.....)

**Comment by FredrikLindgren** [comment]
Works for me too. Closing.
