### ISSUE TITLE
ALTER_ITEM_HEADER is incomplete

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#135]
On **EE** games, it should be possible to set/unset **BIT2** (EE: Damage strength bonus) and **BIT3** (EE: THAC0 strength bonus). They're located at offset 0x026. In other words:
```
LPF ALTER_ITEM_HEADER
INT_VAR
  flag_ee_strength_damage = 1   // or 0
  flag_ee_strength_thac0 = 1      // or 0
END
```

**Comment by FredrikLindgren** [comment]
Done.

**Comment by 4Luke4** [comment]
@FredrikLindgren 

Could you reopen this issue? I forgot about **target count** (located at offset 0x000d) - It should be possible to alter this value too....
