### ISSUE TITLE
Semi-automatic GemRB search path addition

### ISSUE THREAD

**Issue by lynxlynxlynx** [WeiDUorg/weidu#153]
Hey, currently to install mods specifically for GemRB (ie. they modify our unhardcoded files) one has has to pass `--search path/to/extra/files`. It's a chore and easily forgot on subsequent invocations.

@CrevsDaak is playing with a "userspace" implementation, where the mod would just start by asking the user for the path if a specific marking (ini) file is not present to read it from. And then prefix all relevant calls with that base path.

I see two downsides:
- if ever two components or mods modify the same original file, the second modification would overwrite the first
- any macros that do their own lookups won't know about the prefix

So I suggest:
- we standardise on a file name, format and location
- WeiDU init checks for its existence, slurps it and calls add_override_path with it

Thoughts?

**Comment by lynxlynxlynx** [comment]
Argent77 reminded me that thebigg added partial gemrb detection via `gemrb_version.txt`. I see it's used, but nothing actually installs it (gemrb could do it on first run, not before). I don't think a version check is actually needed for what weidu is using it for, so we could repurpose this file's handling.

**Comment by FredrikLindgren** [comment]
I'd be happy to do something. Is it desired for path/to/extra/files to take precedence over other search paths? Otherwise I could add them in some other order; it doesn't have to be with add_override_path.

> Argent77 reminded me that thebigg added partial gemrb detection via `gemrb_version.txt`. I see it's used, but nothing actually installs it (gemrb could do it on first run, not before). I don't think a version check is actually needed for what weidu is using it for, so we could repurpose this file's handling.

Well, it's your call whether the version check is needed or not, but WeiDU needs something to let it know it's a GemRB game.

**Comment by lynxlynxlynx** [comment]
Cool, thanks! We use a different path for things we absolutely want to take precedence, so you don't have to worry about the order (we try to keep it to a minimum too, despite it being sooo tempting). 

This _unhardcoded_ path is used for things that are not present before. If it is somehow already present, the one in the game data files or override dirs will take precedence in our lookups. So you can add it to the internal search path whichever way you want.

I don't know what file format or name you prefer, but let's decide it, so we can start planting it into the installs on first run. I don't know if the version* field will ever be useful, but it could stay too. It would mean the contents can't be just the actual path value though, since there would then be two. For us ini files work fine, but also simpler text that can be slurped with sscanf. I guess both are clearer for users if they want to change them or are just curious.

* our versions are semantic, but between releases there is a -git suffix, so strip that if present.

**Comment by FredrikLindgren** [comment]
> This _unhardcoded_ path is used for things that are not present before. If it is somehow already present, the one in the game data files or override dirs will take precedence in our lookups. So you can add it to the internal search path whichever way you want.

I was thinking of things like `COPY_EXISTING gemrb_file override`
This would work and might be necessary since gemrb_file is located in your unhardcoded path, which would be among the standard search paths, but foo_mod may not know which path it is, and so can't put it as the destination. In this case, override would need to be highest in priority. If that also already takes precedence in gemrb's lookup, that's another reason. So I'll add the path obtained from this as lower in precedence than override.

> I don't know what file format or name you prefer, but let's decide it, so we can start planting it into the installs on first run. I don't know if the version* field will ever be useful, but it could stay too. It would mean the contents can't be just the actual path value though, since there would then be two. For us ini files work fine, but also simpler text that can be slurped with sscanf. I guess both are clearer for users if they want to change them or are just curious.

If I got to choose, I would prefer something that did not need a parser, or JSON, since I need to write a parser for that anyway [1]. The version information is not necessary if gemrb can be identified in another way, unless there are current versions of gemrb which do not have the raised limits for number of kits or musics. Currently, WeiDU's gemrb-awareness is in allowing a greater than vanilla number of those two if the gemrb version is >0.6.6.

1. I largely can't link third-party code due to WeiDU's licence, which waives requirements for the distribution of unmodified binaries.

**Comment by lynxlynxlynx** [comment]
I'll repeat a bit to make sure we're on the same page.
When it comes to data already with the game or added by mods, gemrb mimics the originals' lookup priority. Our unhardcoded/ is almost the same as existing data (could be called "missing data") and if modded, should end up in the game override. There is no need to install into our unhardcoded/ and it would fail on many systems anyway. So yes, I take it back, the game override should have precedence.

On the other hand our override/ is not something to be touched at all. It's a hard override, so no matter where you create copies of those files, we will ignore it. So you can forget we even have it.

0.6.* versions are so old (2011) that nobody is running them for sure. GemRB is constantly evolving, still basically a beta, so it would be super silly. Presence can be identified by the same file with the path. JSON would be fine for us, since while we also don't have a parser, writing this little file is trivial. 

But if we only need to store the path, there's no need for structure and we just have to decide on the file name and the contents can just be the actual path or something like `GemRB_Data_Path = /a/a/a/a/` to be clearer to users (and lhs is easy to strip). I prefer the simpler approach, since it would also mean it can get done sooner. So I propose the latter and `gemrb_path.txt` as the new name.

**Comment by FredrikLindgren** [comment]
Implemented in b6e05eb71f3c36241e4ec2a578339479b9286e9b.

Will you be leaving gemrb_version.txt as it was or should I update that check?

**Comment by lynxlynxlynx** [comment]
It was never there, Valerio didn't communicate it well enough.

**Comment by FredrikLindgren** [comment]
I'll update the check, then. What's a reliable way of detecting GemRB? Argent77 checks for GemRB.log or gem-baldur.ini in code ve recently wrote. I should probably add an ENGINE_IS for this, as well.

**Comment by lynxlynxlynx** [comment]
I suggested that, but they also won't be there until the first run, so gemrb_path.txt is good enough. Checking if gemrb is in PATH would be unreliable, so I don't think we can do any better.

**Comment by FredrikLindgren** [comment]
Ok. Thank you.

**Comment by lynxlynxlynx** [comment]
Sorry, now that I'm doing our half of the equation, I see I overlooked one thing. In our path, we have per-gametype subfolders and one "shared/", for shared files. The latter is trivial to add, but for the first, we need a mapping. If I go from https://github.com/WeiDUorg/weidu/blob/b26ebf21541dc722485b4948b5b058b19c8a28c7/test/tp2/tp2_regression_tests/data/games.tpa, these remain:

>   soa -> bg2
>   tob -> bg2
>   totsc -> bg1
>   iwd1 -> iwd
>   totlm -> how
>   tutu, tutu_totsc (?), bgt and ca should also be bg2.

And then the search path addition should add the base path in the file twice:
- once concatenated with a path delimiter and "shared"
- once concatenated with a path delimiter and the modified GAME_IS from above

**Comment by lynxlynxlynx** [comment]
Or I can dump the gametype path and you strip the last dir to have an easier time and just generate "shared" from that. Or I can dump two paths ... Let me know how you want to proceed.

**Comment by CrevsDaak** [comment]
> Or I can dump the gametype path and you strip the last dir to have an easier time and just generate "shared" from that.

This would be the ideal, since you rarely if ever need to access the other games' data.

**Comment by lynxlynxlynx** [comment]
It's trivial for me either way, but yeah, there is no such case where you'd need to access data from other game(type)s. There's always two paths though.

**Comment by lynxlynxlynx** [comment]
We're now planting the file with an absolute path to the gametyped unhardcoded dir, for example: `/home/kajak/games/gemrb/gemrb/unhardcoded/bg2`

The other one is then `/home/kajak/games/gemrb/gemrb/unhardcoded/shared`.

This was the only thing left on our plate before the release, so please give me some confirmation, before I package it all up. I wouldn't like to wait (on our end) for another cycle, before this is usable.

**Comment by FredrikLindgren** [comment]
Can you post a complete example of what a file might look like now?

**Comment by lynxlynxlynx** [comment]
If this approach is fine for you, since it still requires weidu changes — now only one of the two search paths is added.

**Comment by FredrikLindgren** [comment]
Should be fine.

**Comment by lynxlynxlynx** [comment]
These paths always exist (https://github.com/gemrb/gemrb/tree/master/gemrb/unhardcoded). If the same filename is in both, the one in the typed dir should be used instead of the shared one.
