### ISSUE TITLE
The documentation about ADD_SPELL should be slightly tweaked

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#154]
It states:
**ADD_SPELL** newSPLfile

This is probably better:
**ADD_SPELL** modpath/SPLName.SPL

**Comment by FredrikLindgren** [comment]
I'll clarify that newSPLfile should include path and extension.

**Comment by 4Luke4** [comment]
> I'll clarify that `newSPLfile` should include path and extension.

Yeah, it's basically the same as **ADD_PROJECTILE**.......
