### ISSUE TITLE
The index of ReadMe should include references to all sections

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#156]
The last reference is `12.2  sc#addWmpAre`, so the following sections are missing (and should therefore be included):

- 13  `Module Distribution: Setup-MyMod.exe`
- 13.1  Module Distribution Conventions
- 13.2  WeiDU Return Values
- 14  Regular Expressions
- 15  WeiDU `constant`s
- 16  Common File Formats
- 17  The Source Code
- 18  `Special Thanks`
- 19  Informal Copyright Notice
- 20  Undocumented Features
- 21  Index of Terms
- Index

**Comment by FredrikLindgren** [comment]
The HeVeA conversion process breaks on the escaped number sign in sc#addWmpAre and everything after that is lost from the index. I can't think of a good solution short of omitting sc#addWmpAre from the index.

**Comment by 4Luke4** [comment]
> The HeVeA conversion process breaks on the escaped number sign in sc#addWmpAre and everything after that is lost from the index. I can't think of a good solution short of omitting sc#addWmpAre from the index.

I see.
Well, you could edit the underlying `LaTeX` code and change the name of that `\subsection` into "Adding an area to the worldmap" (or something like that). After that, you could edit the beginning of the paragraph so to read:
`sc#addWmpAre`: _Adds an area to the worldmap. All variables are zero or blank by default unless otherwise indicated. This is an ACTION function._

**Comment by burner1024** [comment]
Maybe it's time to look for an alternative to latex? Something jekyll-based? It would really help to have the doc in machine readable format, at least partly.

**Comment by lynxlynxlynx** [comment]
LaTeX also supports escaping (\#) and since you're already preprocessing the content, it's simple to fix in:
https://github.com/WeiDUorg/weidu/blob/master/doc/Makefile
