### ISSUE TITLE
Executable Missing from WeiDU-Mac-246.zip

### ISSUE THREAD

**Issue by douglasbeagley** [WeiDUorg/weidu#158]
Hello,
The WeiDU-Mac-246.zip file does not appear to contain an executable or .command for running in macOS.
best,
d

**Comment by FredrikLindgren** [comment]
Hi,
The WeiDU executable is located in `WeiDU-Mac/bin/$ARCH/` where `$ARCH` is your choice of 64-bit (AMD64) or 32-bit (x86). There is no command file, no.
