### ISSUE TITLE
The documentation about SAY and SAY_EVALUATED should be tweaked

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#163]
Unless I'm missing something, `SAY offset reference` is valid syntax too, but only when `reference` is `@integer`.

As a result, documentation should be updated accordingly.

**Comment by FredrikLindgren** [comment]
Yes, the correct syntax for `SAY` is `SAY offset text`, where `text` is [text](https://weidu.org/~thebigg/README-WeiDU.html#text). For `SAY_EVAULATED`, however, it must be a string literal.
