### ISSUE TITLE
[ACTION_MATCH / PATCH_MATCH] Documentation should clearly state that guardvalues can be regexps.

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#169]
Pretty much what the title states.

Documentation is currently pointing to [value](https://weidu.org/~thebigg/README-WeiDU.html#value). It should point to [regexp](https://weidu.org/~thebigg/README-WeiDU.html#regexp).

**Comment by 4Luke4** [comment]
Guess the same holds for `ACTION_TRY / PATCH_TRY`.

**Comment by FredrikLindgren** [comment]
No, the guard values must be [value](https://weidu.org/~thebigg/README-WeiDU.html#value)s. However, the documentation for the match value and the condition value is off, and I'll clarify.

**Comment by FredrikLindgren** [comment]
Should hopefully be clearer now.
