### ISSUE TITLE
CLONE|DELETE|ALTER_EFFECT: wrong datatype

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#170]
https://github.com/WeiDUorg/weidu/blob/c1e885d683731632e51df2a3c0b6bd89f64682ac/src/tph/include/cd_functions.tpa#L1240

@CamDawg 
It should be `READ_BYTE` instead of `READ_SHORT`.

**Comment by FredrikLindgren** [comment]
Good catch. CLONE_EFFECT is unable to match abilities on type if the second byte is not zero. Will fix.

**Comment by 4Luke4** [comment]
> Good catch. CLONE_EFFECT is unable to match abilities on type if the second byte is not zero. Will fix.

The same holds for `ALTER_EFFECT` and `DELETE_EFFECT`.

**Comment by FredrikLindgren** [comment]
Fixed. Thanks.
