### ISSUE TITLE
[Feature Request] CLEAR_VARIABLE

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#172]
Pretty much what the title states.

Is there any particular reason why there's no `CLEAR_VARIABLE` command?
I mean, we have both `CLEAR_ARRAYS` and `CLEAR_ARRAY` so why is there no way to clear a specific variable? Or just some variables (e.g. MATLAB-style: `clear var1 ... varN` or `clear -regexp ^Mon ^Tue ^Wed`)?

Guess the same holds for `CLEAR_INLINED` and `CLEAR_CODES`, i.e.: there should be a way to clear a specific inlined file (or the listed inlined files) and/or a specific function (or the listed functions).

**Comment by FredrikLindgren** [comment]
I rather feel variable-scopes is the proper way to handle this. If you need one or more variables to not exist after some code has executed, that's arguably a sign you should have used a function. If you need set up variables for some throw-away purpose, there is also WITH_SCOPE.

**Comment by 4Luke4** [comment]
> If you need to set up throw-away variables for some purpose, there is also WITH_SCOPE.

Good to know, that's what I was looking for...
So basically that command is equivalent to launch a function that returns nothing, right?

**Comment by FredrikLindgren** [comment]
Any variables set inside the scope and any changes made are discarded when the scope exits, so it's a bit like a function, yes.

**Comment by FredrikLindgren** [comment]
So that obviates the need for CLEAR_VARIABLE, then?

What's the use cases for the proposed changes to CLEAR_INLINED and CLEAR_CODES? For either, you can achieve the desired effect by using the present actions and re-including the stuff you did not want cleared. Is clearing specific inlined files or functions something you'd ever actually do? Functions you never call are a non-issue, functions you want to re-implement do not need to be cleared first, inlined files you do not load are likewise a non-issue and if you shadowing real files you are arguably doing it wrong.

**Comment by 4Luke4** [comment]
> So that obviates the need for CLEAR_VARIABLE, then?

Yes. I'm currently using it to check for the presence of `AUTO_EVAL_STRINGS`.
```
WITH_SCOPE BEGIN
	OUTER_TEXT_SPRINT "var" "test"
	OUTER_TEXT_SPRINT "var2" "var"
	ACTION_IF !("%%var2%%" STRING_EQUAL "test") BEGIN
		FAIL "AUTO_EVAL_STRINGS is not set"
	END
END
```
Anyway, as I realized afterwards, that is equivalent to launch a function with no return value.

> Is clearing specific inlined files or functions something you'd ever actually do?
Yeah, probably not.
To be honest, I opened this issue because I thought about MATLAB where you can indeed clear specific items from the memory. However, that's probably not necessary in WeiDU... and even in MATLAB you can apply functional programming, so I guess you can close this issue...

**Comment by 4Luke4** [comment]
> Is there something I'm overlooking?

@FredrikLindgren 
What can you tell me about [multi-dimensional arrays](https://forums.pocketplane.net/index.php?PHPSESSID=8pmmu9qe5elg37uuphpavs37r1&topic=29987.msg340778#msg340778)...?
