### ISSUE TITLE
[Feature request] More REGEXP options

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#176]
What about implementing some of these constructs?

- Positive lookahead `(?=...)`
- Negative lookahead `(?!...)`

- Positive lookbehind `(?<=...)`
- Negative lookbehind `(?<!...)`

**Comment by FredrikLindgren** [comment]
You are already experiencing the full power of OCaml's regexp library, which is pretty much the only thing I can link, due to WeiDU's licence (and I'd bet there'd be compatibility concerns, too).

**Comment by 4Luke4** [comment]
OK, I see.

To be honest, you can approximate, for instance, negative lookahead with something like this
`\([^a].*\|a[^b].*\|ab[^c].*\)`
The problem is that it disallows the forbidden sequence in one particular place in the given string and it doesn't combine well with other regexp constructs.

Guess I'll consider manipulating the given string beforehand (via `REPLACE_TEXTUALLY` or `STRING_CONTAINS_REGEXP`...)
