### ISSUE TITLE
Splitting BACKUP keyword via '\' fail when contains ~\MyMod\backup~

### ISSUE THREAD

**Issue by ALIENQuake** [WeiDUorg/weidu#179]
The mod will then create a backup at the root of the drive where the game is installed. Does having`\` as the first character is a supported case?

**Comment by FredrikLindgren** [comment]
As a leading slash is an absolute path in *nix, I'd probably say no, it isn't. I'm aware WeiDU does not properly handle TP2 paths that are not relative to the game directory, or equivalent, and I will fix that.

**Comment by FredrikLindgren** [comment]
The absolute-path thing should be fixed in e8d36d1a793ca638809acd8b86ad3df60ab0422b.
