### ISSUE TITLE
WeiDU's auto-update should not fail for setup filenames with spaces

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#189]
Reported here: https://forums.beamdog.com/discussion/comment/1165415/#Comment_1165415

How to repro:
- Add a mod with spaces in the setup binary filename using an older WeiDU version.
- Add another mod with a more recent WeiDU version.
- Execute the setup binary of the first mod (with spaces).

**Comment by FredrikLindgren** [comment]
The issue should be fixed in 28d3ae19d9e301feefcc8eddfca209eb97274845
