### ISSUE TITLE
Always get "Press Enter for more options" with --help

### ISSUE THREAD

**Issue by arp242** [WeiDUorg/weidu#194]
$ ./weidu --help
	[/home/martin/WeiDU-Linux/weidu] WeiDU version 24700
					WeiDU (version 24700: "Return of the Warlock")
	[...]

		Press Enter For More Options

This is a bit annoying; it looks like it's because of a rather naïve terminal check, which checks just for `xterm`: https://github.com/WeiDUorg/weidu/blob/a4048b11e6904f39ea1f956a36018e5d9a6e8e5c/src/myarg.ml#L60

My `$TERM` is `st-256color` though.

`TERM=xterm ~/WeiDU-Linux/weidu --help` works as expected.

Not sure why that check is there in the first place 🤔

**Comment by FredrikLindgren** [comment]
It's probably there for the (legacy) Windows command prompt. I don't know how the new PowerShell stuff behaves. I can probably add something to recognise st, probably konsole, as well.
