### ISSUE TITLE
Arrays as arguments to functions

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#198]
[Documentation](https://weidu.org/~thebigg/README-WeiDU.html#sec-functions) should probably mention that it is not possible to pass arrays as arguments to functions. However, you can pass the array name for use in a function.

See [here](https://forums.pocketplane.net/index.php?topic=29786.msg339561#msg339561) for further details.

**Comment by FredrikLindgren** [comment]
> However, you can pass the array name for use in a function.
I mean, I would have said everyone realises that, but apparently not? I'm still not going to mention this under functions, because it's basically how-to-TP2 and it does not belong there.
