### ISSUE TITLE
Improve description of fj_are_structure function

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#206]
There is no explicit list of supported structure types in the WeiDU documentation. The current list of `fj_structure_type` entries looks more like a descriptive list with several names not matching the expected keywords:
  - explored bitmask -> bitmask
  - songlist -> songs
  - rest interrupt table -> interrupts

Misspelled parameter name for projectile traps:
- `fj_embedded_eff0` -> `fj_embedded_eff_0`

Maybe also add a remark that `fj_embedded_eff_x` is treated as an indexed list of parameter names.

**Comment by FredrikLindgren** [comment]
Should be addressed in f003314e08cec4b5cd6e12a38c1736fb56a1ccbb.
