### ISSUE TITLE
Performance issues when installing mods with LABELs

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#208]
Mods which make heavy use of `LABEL` introduce a considerable delay between individual stages of the installation process (up to several seconds) when they are installed in interactive mode.

Candidate for testing: [Tweaks Anthology v10 RC1](https://www.gibberlings3.net/forums/topic/33350-new-testing-version-of-tweaks-anthology-v10-rc1-now-available/)

**Comment by FredrikLindgren** [comment]
Intriguing. And only from simply having LABELs in the TP2.

**Comment by FredrikLindgren** [comment]
Fixed in dcfe95f659e8578cb5df08dc20e11f47195f6632.
