### ISSUE TITLE
Function for retrieving list of game resource names

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#210]
Request for a function, similar to `GET_FILE_ARRAY`, that allows you to retrieve a list of game resource names based on a regexp pattern (maybe call it `GET_RESOURCE_ARRAY`).

Assembling such a list is currently only possible by abusing `COPY_EXISTING_REGEXP` (unless I'm missing something), which is not only a very expensive operation but also fails for large files (>16 MB).

**Comment by FredrikLindgren** [comment]
Should the result be the union of key-indexed files as well as files that exist in the override but not in the KEY, or one or the other?

**Comment by Argent77** [comment]
I'd prefer the same behavior as `COPY_EXISTING` and the like (i.e. include biffed and/or override files). I don't think there are many use cases where a distinction between KEY'ed and non-KEY'ed files is needed.

**Comment by FredrikLindgren** [comment]
Done in d3b201cc756d6d2e1d24b1abc37f8dbd9d263e5a.
