### ISSUE TITLE
Improve description of ADD_MEMORIZED_SPELL patch command

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#211]
Documentation should probably mention that this patch will also cause the given spell to be known.

In other words, there's no need to include `ADD_KNOWN_SPELL ~SPPR314~ #2 ~priest~` in your code.
`ADD_MEMORIZED_SPELL ~SPPR314~ #2 ~priest~ (5)` will automatically do that for you.

**Comment by FredrikLindgren** [comment]
Done in 261abb8f71324a596d4fcb48376d550933f820ae.
