### ISSUE TITLE
[Feature request] Batch-Controlling and batch-installation of add-ons

### ISSUE THREAD

**Issue by rubyFeedback** [WeiDUorg/weidu#220]
Heya,

weidu works fairly well, but it is a bit cumbersome to use.

There are also some add-ons that are incompatible with other
add-ons and then it is difficult to figure out what is going on.

I would like to propose for weidu to get a minimal GUI that
can be used to uninstall / reinstall add-ons easily. This GUI
can be minimal, just a simple drop down listing, and then
perhaps a button to indicate which entry to delete, or lateron
reinstall. Furthermore perhaps some in-GUI way to keep
track of it.

This can be in addition to the commandline executable.

As a user I would like to be able to more easily re-arrange
add-ons, and easily get rid of those that are incompatible.

Batch-installation would be nice too for instance:

    weidu.exe --install-from-the-current-directory

Or something like that. This could be used to batch-install
all entries there and registered them into a log file.

**Comment by ALIENQuake** [comment]
@rubyFeedback Check this: ProjectInfinity https://forums.beamdog.com/discussion/74335/project-infinity-public-beta-for-all/p1

**Comment by FredrikLindgren** [comment]
No GUI will be added to WeiDU itself (for technical reasons). There is a graphical front-end "developed" by me, making it the official graphical front-end, [here](https://github.com/WeiDUorg/zeitgeist). There are, as ALIENQuake posts, other options. WeiDU does have some ability to do batch-installations, but `--process-script` is undocumented and I have to plans to expand on it. I think it's something better done from another program or script.
