### ISSUE TITLE
Cannot copy array defined by READ_2DA_ENTRIES_NOW

### ISSUE THREAD

**Issue by SarahG-579462** [WeiDUorg/weidu#221]
the following snippet doesn't set the array outtable
 `

      DEFINE_ACTION_FUNCTION 2DA_TO_ASARRAY 
        STR_VAR filename = ~~
                fileto = ~override~
        RET_ARRAY
          outtable
        BEGIN 
          COPY_EXISTING "%filename%" "%fileto%"
            COUNT_2DA_COLS "ncols"
            READ_2DA_ENTRIES_NOW "outtable" "%ncols%"
            BUT_ONLY
      END

`

I suspect this is because READ_2DA_ENTRIES_NOW also sets the variable %outtable% = number of 2da rows.

**Comment by sg2475962** [comment]
temporary (dumb) solution:
`
      FOR (row=0; row < "%outtable%"; row += 1) BEGIN
        FOR (col=0; col < "%ncols%"; col += 1) BEGIN
          SPRINT $outtable2(row col) $outtable(row col)
        END
      END

`
