### ISSUE TITLE
Is it possible to compile new weidu releases automatically, say, every 6-12 months?

### ISSUE THREAD

**Issue by rubyFeedback** [WeiDUorg/weidu#223]
Is it possible to compile new weidu releases automatically, say, every 6-12 months?

Last release has been in 2021. I understand that not many things may have changed
but I feel better with more recent weidu variants. Some mods cause issues and 
weidu has problems with these. Finding out what the root cause is is not so trivial.

For instance, lately, after installing many mods, when I start a new game, I see the
hand (cursor of the mouse pointer) but the game is not loaded. So some mod 
blocks the loading somehow. I will eventually narrow it down to the mod that does
so, but finding this out is not so trivial. A new weidu may be nice to have; I intend
to use weidu from the commandline rather than depend on mods coming with
weidu (this is also a problem, they always seem to want to carry their own weidu
executable; would be better if everyone instead could go to the github repository
here. There is even the old weidu homepage from 2009 still about!).

**Comment by FredrikLindgren** [comment]
Unfortunately not. WeiDU's build process is not amendable to automation. Additionally, development comes in fits and spurts, so it's not suitable for time-based releases.
