### ISSUE TITLE
[Feature request] Add optional parameter to ADD_PROJECTILE action: Symbolic name for MISSILE.IDS

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#224]
Descriptive symbolic names for projectile entries in `MISSILE.IDS` will be helpful when working with projectiles in resource editors.

**Comment by FredrikLindgren** [comment]
This is undocumented but already exists.
`ADD_PROJECTILE "%MOD_FOLDER%/fl#pro.pro" funnybeans` will give the projectile the name funnybeans in MISSILE.IDS. Will document.
