### ISSUE TITLE
HANDLE_CHARSETS: Add Portuguese language support to "infer_charset" option

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#229]
As of WeiDU v249 the charset conversion list of `HANDLE_CHARSET` doesn't include (Brazilian) Portuguese language detection.

**Comment by ALIENQuake** [comment]
Had this problem too, 👍🏻

**Comment by FredrikLindgren** [comment]
So regexp for brazilian, portuguese, pt_BR. Anything else? I assume this is another case of CP1252?

**Comment by Argent77** [comment]
I think that's all. I haven't encountered other mod languages yet that are not supported by HANDLE_CHARSET.

(There's also [Almateria's Restoration Project](https://github.com/SpellholdStudios/Almaterias_Restoration_Project/blob/main/arestorationp/arestorationp.tp2#L33-L47) containing several exotic languages, but I don't think they require explicit support.)
