### ISSUE TITLE
Aarch64 build

### ISSUE THREAD

**Issue by a-priestley** [WeiDUorg/weidu#230]
Hello,
I'm wondering if it's possible to target aarch64 architecture when building weidu. I've been successful in building gemrb on arm, and it would be really cool to be able to get infinity engine mod support as well. 
Is this doable? I'm assuming that elkhound will need to be built for it as a prerequisite, or can I use it as-is for cross-compilation?
I'm new to ocaml -- any guidance is greatly appreciated!

**Comment by FredrikLindgren** [comment]
I don't know much about OCaml on Arm. They state they added aarch64-output to the native compiler with 4.02, but I don't know if that means all the pieces needed to build WeiDU are in place. Elkhound only needs to run on the build system and outputs input for OCaml, so a cross-compiling build environment would not need Aarch64-elkhound, assuming OCaml can do cross-compilation. I can't help you more than that, I'm afraid.
