### ISSUE TITLE
HANDLE_CHARSETS: Add Swedish language support to "infer_charset" option #229

### ISSUE THREAD

**Issue by ALIENQuake** [WeiDUorg/weidu#234]
@FredrikLindgren Missed the update of #229, I got one more: `"Swedish", "sv_SE", "CP1252"`.

**Comment by ALIENQuake** [comment]
Ascension mod has a translation for both Swedish and Portuguese. I wold like to not having to define custom charset table for common languages.

**Comment by FredrikLindgren** [comment]
Done in 1e5080ea5304ba6a5a639376dd15dbe63db7138a.
