### ISSUE TITLE
Adding an actor using fj_are_structure causes a read out-of-bounds error.

### ISSUE THREAD

**Issue by LCA-EET** [WeiDUorg/weidu#241]
Hi,

I'm working on a mod that involves copying and extending a BG1 area, AR0608. I'm trying to add two new actors to the area using fj_are_structure. I'm able to add one without issue, but when I try adding the second, I get an out of bounds error. It's strange because I've used this approach on other BG1 areas without issue.

The code from my .tph file and the error message are provided below. A copy of the .are file is attached.

COPY ~%MOD_FOLDER%/rbg/are/ar0608.are~ ~override~
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 380
				fj_loc_y = 309
				fj_orientation = 4 // W 
			STR_VAR
				fj_structure_type = actor
				fj_name = Kent
				fj_cre_resref = xakent
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 233
				fj_loc_y = 399
				fj_orientation = 11 // ENE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Nederlok
				fj_cre_resref = xanederl
		END

Error Text 
ERROR: illegal 228-byte read from offset 2144 of 2144-byte file LCA/rbg/are/ar0608.are
ERROR: [LCA/rbg/are/ar0608.are] -> [override/ar0608.are] Patching Failed (COPY) (Failure("LCA/rbg/are/ar0608.are: read out of bounds"))

I don't believe its a .cre issue, as I'm able add any .cre as an actor so long as only one actor is added. It's the addition of the second actor using fj_are_strcture that is causing the issue. I've tried doing another copy and modification of the area modified after the first actor addition, but I received the same error. 
[AR0608.zip](https://github.com/WeiDUorg/weidu/files/15276848/AR0608.zip)
Any insight would be appreciated, thanks.

**Comment by FredrikLindgren** [comment]
I would guess there is some unexpected quirk to the ARE file that causes fj_are_structure to create a patched ARE that may be technically valid, but sets subsequent patches up to fail. I'll look into it.

**Comment by LCA-EET** [comment]
No rush, thanks. I appreciate it.

**Comment by Argent77** [comment]
The attached ARE file does not contain a Rest Encounter structure. Offset to that structure is initially `0x0` which apparently instructs "fj_are_structure" to ignore it in the first function call.

After the first actor is added the Rest Encounter offset is updated with a nonzero value which seems to trigger the error in the second function call.

**Comment by LCA-EET** [comment]
Thanks for looking into it. To reset the rest encounter offset back to zero, I added the following line between the two calls to fj_are_structure.

WRITE_LONG 0xC0 0 // Rest Encounter Offset Bug Fix

This fixed the problem. Thanks again for the help.

**Comment by Roberciiik** [comment]
Potentially a proper fix would be to add an empty Rest Encounter section, so each following area change would not generate such issue again.

**Comment by Argent77** [comment]
> Potentially a proper fix would be to add an empty Rest Encounter section, so each following area change would not generate such issue again.

I would suggest that too. An ARE file can be considered malformed if it lacks Song and Rest Encounter structures since these cannot be automatically detected under all circumstances.

**Comment by LCA-EET** [comment]
Adding a call to fj_are_structure to include a disabled rest interrupt (before the calls to add the creatures to the area) did the trick. Thanks for the suggestion.
