### ISSUE TITLE
New resource types (MENU, LUA, TTF, PNG)

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#78]
Patch 2.0 of the Enhanced Editions provides support for the following resource types:
- `MENU` = `0x408`
- `LUA` = `0x409`
- `TTF` = `0x40a`
- `PNG` = `0x40b`

The following resource types are also supposed to work (untested):
- `TOT` = `0x406`
- `TOH` = `0x407`

**Comment by FredrikLindgren** [comment]
Done.
