### ISSUE TITLE
Flags parameter of ADD_STORE_ITEM should support variable evaluation

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#82]
Variables are not evaluated for the flags parameter of ADD_STORE_ITEM.

Example:
```
COPY_EXISTING ~25spell.sto~ ~override~
  TEXT_SPRINT flags ~identified~
  ADD_STORE_ITEM ~scrl01~ LAST #1 #0 #0 ~%flags%~ #5
```
Triggers the warning `ADD_STORE_ITEM: Unknown flag %FLAGS%. Defaulting to 0 for flags.`

ADD_CRE_ITEM is not affected.

**Comment by FredrikLindgren** [comment]
Fixed.
