### ISSUE TITLE
Linux weinstall not finding .tp2 files

### ISSUE THREAD

**Issue by mmatis** [WeiDUorg/weidu#87]
Using Linux x86_64, version 240.  If I run weinstall in a game directory and point to a mod with uppercase letters in its name, it states that it cannot find a .tp2 file. If weinstall is just a "runner" for weidu, I think it must be passing lowercased filenames to weidu. If I lowercase the names of the mod folder and .tp2, it can find it. Running weidu directly and pointing directly to the mixed-case .tp2 works.

**Comment by FredrikLindgren** [comment]
Yes, WeInstall lowercases the name of the TP2. Historically, WeiDU has only supported all-lowercase games in case-sensitive environments.
