### ISSUE TITLE
WeiDU uses invalid pathname separators when updating chitin.key in EE games

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#88]
WeiDU currently uses backslash characters in pathnames to biff files in the chitin.key. This separator is incompatible with non-Windows versions of Enhanced Edition games and also incompatible with the chitin.key found in DLC archives such as used for the Siege of Dragonspear expansion (all platforms).

Instead, WeiDU should use forward slashes in these cases. The Windows version does currently have no issues with backslashes. However, the chitin.key of games for this platform is also using forward slashes by default.

Related discussion: http://gibberlings3.net/forums/index.php?showtopic=28337&p=250603

**Comment by FredrikLindgren** [comment]
Does slash work for all versions of EE on all platforms?

**Comment by Argent77** [comment]
Forward slashes are used by default on Windows versions of BG1EE/SoD, BG2EE and IWDEE (all patch versions). 

Chitin.key on macOS, Linux and embedded in DLC archives require forward slashes (confirmed in patch v2.0 and higher, but will most likely work in <2.0 as well).

**Comment by FredrikLindgren** [comment]
Fixed.
