### ISSUE TITLE
BCS compiler/decompiler does not correctly handle colon-separated string parameters (IWD and IWD2)

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#90]
Script triggers and actions using colon-separated strings are incorrectly encoded or decoded. Trigger `GlobalBitGlobal` can't be decoded at all.

Problematic triggers:
- `0x40A5 BitGlobal(S:String1*,S:String2*,I:Value,I:Mode*BitMode)`
- `0x40A6 GlobalBitGlobal(S:String1*,S:String2*,S:String3*,S:String4*,I:Mode*BitMode)`

Problematic actions:
- `247 BitGlobal(S:String1*,S:String2*,I:Value,I:Mode*BitMode)`
- `248 GlobalBitGlobal(S:String1*,S:String2*,S:String3*,S:String4*,I:Mode*BitMode)`
- `306 SetGlobalRandom(S:Name*,S:Area*,I:Min*,I:Max*)`
- `307 SetGlobalTimerRandom(S:Name*,S:Area*,I:Min*,I:Max*)`
- `289 SpellCastEffect(O:Source*,S:Voice*,S:Sound1*,S:Sound2*,I:Animation*sceffect,I:Speed*,I:Sequence*Sequence)`

`SpellCastEffect` is not used in IWD2, so I had to deduce the string format based on argument types. Chances are high that `S:Voice*` is stored in first string parameter, and `S:Sound1*` as well as `S:Sound2*` are sharing second string parameter using colon-separator to tell them apart.

Test script in BCS and BAF version with all affected IWD2 triggers and actions: [testscript_iwd2.zip](https://github.com/WeiDUorg/weidu/files/780410/testscript_iwd2.zip)

**Comment by Argent77** [comment]
Looks like I was wrong about `SpellCastEffect()`. It is used in several vanilla game scripts, and the encoded string format is as suggested in the previous comment. (Example: `67CTELPC.BCS`)

**Comment by FredrikLindgren** [comment]
Fixed. Thanks for the test case.
