### ISSUE TITLE
Symbolic SUBRACE values are resolved incorrectly for IDS targets (IWD2)

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#91]
Entries in SUBRACE.IDS consist of combined RACE + SUBRACE values.

The RACE value makes up the higher word and should be removed when compiling IDS targets. The reverse process should ideally take RACE values into account when looking up the correct SUBRACE symbol.

Example 1: Compiler
`See([0.0.ELF.0.0.0.0.ELF_DROW],0)` should be resolved into `See([0.0.2.0.0.0.0.1],0)`.

Example 2: Decompiler
`OB 0 0 2 0 0 0 0 1 0 0 0 0 0 [-1.-1.-1.-1] "" 0 0 OB` should be decoded into `[0.0.ELF.0.0.0.0.ELF_DROW]`, while `OB 0 0 4 0 0 0 0 1 0 0 0 0 0 [-1.-1.-1.-1] "" 0 0 OB`* should be decoded into `[0.0.DWARF.0.0.0.0.DWARF_GOLD]` instead.

Trigger `0x40CD SubRace(O:Object*,I:SubRace*SubRace)` appears to use values from SUBRACE.IDS directly.

**Comment by FredrikLindgren** [comment]
Fixed.
