### ISSUE TITLE
Log message of APPEND doesn't evaluate variables in 'when' clause.

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#92]
Example:
```
OUTER_TEXT_SPRINT identifier ~MY_IDENTIFIER~
APPEND ~specific.ids~ ~123 %identifier%~ UNLESS ~%identifier%~
```

Returns
`Appending [123 MY_IDENTIFIER...] to [specific.ids] because it does NOT contain [%identifier%]`
or
`Not appending [123 MY_IDENTIFIER...] to [specific.ids] because it DOES contains [%identifier%]`

The WeiDU command itself works correctly though.

**Comment by FredrikLindgren** [comment]
Fixed. Thanks.
