### ISSUE TITLE
BCS script decompiler produces incorrect TriggerOverride() statement

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#93]
The trigger statement `TriggerOverride(Player1,IsOverMe("viconia"))` is incorrectly decompiled from its bytecode representation. The closing round parenthesis of `TriggerOverride()` is placed inside generated script name comment.

How to reproduce (on BGEE or BG2EE):
1. Add above trigger statement into BAF
2. Compile BAF to BCS
3. Decompile BCS back to BAF

Resulting trigger is `TriggerOverride(Player1,IsOverMe("viconia")  // viconia)`.

**Comment by FredrikLindgren** [comment]
Fixed.
