### ISSUE TITLE
The script compiler should apply stricter checks when evaluating numeric function parameters

### ISSUE THREAD

**Issue by Argent77** [WeiDUorg/weidu#94]
Currently it is possible to specify string arguments as integer parameters without the compiler triggering error or warning messages. The compiler attempts to convert it into a numeric or symbolic value and falls back to using 0 if the conversion fails.

This behavior may cause unexpected and difficult to find side effects when used in functions where the arguments can be mistakenly assumed to be strings instead of numeric type, such as for `StartTimer()` and `TimerExpired()` which is even suggested by [this IESDP script example](https://gibberlings3.github.io/iesdp/scripting/actions/bgeeactions.htm#61).

**Example:**
```
IF
  TimerExpired("ShortPeriodTimer")
THEN
  RESPONSE #100
    StartTimer("ShortPeriodTimer", 6)
END

IF
  TimerExpired("LongPeriodTimer")
THEN
  RESPONSE #100
    StartTimer("LongPeriodTimer", 30)
END
```
The script compiles without complains. However, both string arguments are converted to 0 which prevents the second block from being processed at all.

Parameters expecting symbolic values are affected as well. The compiler throws a message of not finding the symbol in the implied IDS file, but still continues to compile the script.

**Comment by FredrikLindgren** [comment]
I can give you a warning when defaulting to 0 happens, but failing installations over this is too backward-incompatible.

**Comment by Argent77** [comment]
A warning should work too as long there is some feedback about a potential issue.

**Comment by FredrikLindgren** [comment]
It'll be like with unfound IDS symbols.
