### ISSUE TITLE
HANDLE_CHARSETS and PST:EE

### ISSUE THREAD

**Issue by badungu** [WeiDUorg/weidu#98]
Hi there,

I tested today the HANDLE_CHARSETS function with PST:EE and it doesn't work, because the MONKFIST.2da and SW1H01.itm does not exist ingame. Maybe it's better to add a check for BGEE.lua (Maybe change this to   ACTION_IF FILE_EXISTS_IN_GAME monkfist.2da OR FILE_EXISTS_IN_GAME bgee.lua BEGIN) and change the copying of SW1H01.itm to BOLT01.itm which is present in all games. 

Thanks for your hard work on keeping weidu up-to-date! :)

badungu

**Comment by FredrikLindgren** [comment]
Fixed. Thanks.
