### ISSUE TITLE
Iterations and Index inside WMP_NORTH/WEST/SOUTH/EAST_LINKS are wrong

### ISSUE THREAD

**Issue by badungu** [WeiDUorg/weidu#99]
Hi,

tried today the pre-defined values (WMP_NORTH/WEST/SOUTH/EAST_LINKS) for GET_OFFSET_ARRAY2.
I think the Iterations and Index are switched and produces wrong results.
The right values should be:

WMP_NORTH_LINKS (0x38 4 **0x54** 4 **0x50** 4 0xd8)
WMP_WEST_LINKS (0x38 4 **0x5c** 4 **0x58** 4 0xd8)
WMP_SOUTH_LINKS (0x38 4 **0x64** 4 **0x60** 4 0xd8)
WMP_EAST_LINKS (0x38 4 **0x6c** 4 **0x68** 4 0xd8)

instead of:

WMP_NORTH_LINKS (0x38 4 **0x50** 4 **0x54** 4 0xd8)
WMP_WEST_LINKS (0x38 4 **0x58** 4 **0x5c** 4 0xd8)
WMP_SOUTH_LINKS (0x38 4 **0x60** 4 **0x64** 4 0xd8)
WMP_EAST_LINKS (0x38 4 **0x68** 4 **0x6c** 4 0xd8)

Kind Regards
badungu

**Comment by FredrikLindgren** [comment]
Fixed. Thanks.
